apiVersion: v1
kind: Namespace
metadata:
  name: carapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardatabase-deployment
  namespace: carapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cardatabase
  template:
    metadata:
      labels:
        app: cardatabase
    spec:
      containers:
      - name: cardatabase
        image: mchahoud/cardatabase:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SERVICE_NAME
          value: "cardatabase"
        - name: APM_URL
          value: "https://apm-server-quickstart-apm-http.eck.svc:8200"
        - name: SECRET_TOKEN
          value: "Dqdv74xXZS31QTc3VC22s577" #change it with your token
        - name: ENVIRONMENT
          value: "demo"
        - name: APPLICATION_PACKAGES
          value: "org.demo.carapp"
---
apiVersion: v1
kind: Service
metadata:
  name: cardatabase-service
  namespace: carapp
spec:
  selector:
    app: cardatabase
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
